global:
  measurements:
    - name: podLatency
  clusterHealth: true
jobs:
  - name: hpa-intensive
    jobIterations: 1
    namespacedIterations: true
    podWait: false
    cleanup: true
    waitWhenFinished: true
    objects:
      - objectTemplate: tmp/templates-1/new-temps/namespace.yaml
        replicas: 45
      - objectTemplate: tmp/templates-1/new-temps/Deployment-php.yaml
        replicas: 45
      - objectTemplate: tmp/templates-1/new-temps/service-ClusterIP.yaml
        replicas: 45
      - objectTemplate: tmp/templates-1/new-temps/service-php.yaml
        replicas: 45
      - objectTemplate: tmp/templates-1/new-temps/ServiceMonitor-php.yaml
        replicas: 45
      - objectTemplate: tmp/templates-1/new-temps/Configmap-php.yaml
        replicas: 45
      - objectTemplate: tmp/templates-1/new-temps/HorizontalPodAutoscaler-php.yaml
        replicas: 45
