apiVersion: v1
kind: Service
metadata:
  name: php-service-clusterip-{{.Replica}}
  namespace: ns-{{.Replica}}
  labels:
    kube-burner-job: hpa
    app: apache
    release: prometheus 
spec:
  selector:
    app: apache
    release: prometheus
  type: ClusterIP
  ports:
  - name: metrics
    protocol: TCP
    port: 9117
    targetPort: 9117
